### ISSUE TITLE
Incorrect exit status with invalid args

### ISSUE THREAD

**Issue by abhillman** [whatwg/wattsi#163] opened 2024-12-02 06:01 UTC
**Observed**: if zero or invalid args are provided, `wattsi` exits with a zero status code
**Expected**: exit with a non-zero status code

Caveat: this may or may not be wise to fix due to potentialities of it breaking an existing upstream caller

**Comment by domenic** [comment] 2024-12-02 06:06
Dupe of https://github.com/whatwg/wattsi/issues/77.

No worries about upstream callers; we control them all.

**Closed by domenic** 2024-12-02 06:06 UTC
